//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.8689
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="eUsuarios", Namespace="http://schemas.datacontract.org/2004/07/Entidades")]
    public partial class eUsuarios : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ClaveField;
        
        private string CuentaField;
        
        private string EstadoField;
        
        private int IdAreaField;
        
        private string NombreField;
        
        private string TelefonoField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Clave
        {
            get
            {
                return this.ClaveField;
            }
            set
            {
                this.ClaveField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cuenta
        {
            get
            {
                return this.CuentaField;
            }
            set
            {
                this.CuentaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                this.EstadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdArea
        {
            get
            {
                return this.IdAreaField;
            }
            set
            {
                this.IdAreaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono
        {
            get
            {
                return this.TelefonoField;
            }
            set
            {
                this.TelefonoField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IUsuarios")]
public interface IUsuarios
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarios/Nuevo", ReplyAction="http://tempuri.org/IUsuarios/NuevoResponse")]
    void Nuevo(Entidades.eUsuarios usuario);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarios/Todos", ReplyAction="http://tempuri.org/IUsuarios/TodosResponse")]
    Entidades.eUsuarios[] Todos();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarios/xClave", ReplyAction="http://tempuri.org/IUsuarios/xClaveResponse")]
    Entidades.eUsuarios xClave(string clave);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IUsuariosChannel : IUsuarios, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class UsuariosClient : System.ServiceModel.ClientBase<IUsuarios>, IUsuarios
{
    
    public UsuariosClient()
    {
    }
    
    public UsuariosClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public UsuariosClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public UsuariosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public UsuariosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public void Nuevo(Entidades.eUsuarios usuario)
    {
        base.Channel.Nuevo(usuario);
    }
    
    public Entidades.eUsuarios[] Todos()
    {
        return base.Channel.Todos();
    }
    
    public Entidades.eUsuarios xClave(string clave)
    {
        return base.Channel.xClave(clave);
    }
}
